FROM python:3.10.12-slim

WORKDIR /app

COPY requirements.txt /app/
RUN pip install -r requirements.txt

COPY consumers/ /app/consumers/
COPY app/database.py /app/
COPY run.sh /app/

RUN chmod +x run.sh

CMD ["bash", "run.sh"]
